/** Small real files, embedded so the demo and tests need no disk access. */

/** Decode an embedded base64 fixture into its original bytes. */
const base64 = (text: string) =>
  Uint8Array.from(atob(text), char => char.charCodeAt(0))

/** A 1x1 transparent PNG: signature, IHDR, IDAT, IEND. */
export const tinyPng = base64(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg=="
)

/** A 64-bit little-endian x86-64 executable with .text and .shstrtab sections. */
export const tinyElf = base64(
  "f0VMRgIBAQAAAAAAAAAAAAIAPgABAAAAABBAAAAAAAAAAAAAAAAAAFgAAAAAAAAAAAAAAEAAOAAAAEAAAwACAEgxwMMALnRleHQALnNoc3RydGFiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAQAAAAYAAAAAAAAAABBAAAAAAABAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABwAAAAMAAAAAAAAAAAAAAAAAAAAAAAAARAAAAAAAAAARAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA=="
)

/** A stored (uncompressed) archive holding hello.txt and dir/notes.md. */
export const tinyZip = base64(
  "UEsDBBQAAAAAAIMYIlggMDo2BgAAAAYAAAAJAAAAaGVsbG8udHh0aGVsbG8KUEsDBBQAAAAAAIMYIljd8Hy6CAAAAAgAAAAMAAAAZGlyL25vdGVzLm1kIyBub3RlcwpQSwECFAMUAAAAAACDGCJYIDA6NgYAAAAGAAAACQAAAAAAAAAAAAAAgAEAAAAAaGVsbG8udHh0UEsBAhQDFAAAAAAAgxgiWN3wfLoIAAAACAAAAAwAAAAAAAAAAAAAAIABLQAAAGRpci9ub3Rlcy5tZFBLBQYAAAAAAgACAHEAAABfAAAAAAA="
)
